#  VECTOR AND MATRICES IN PYTHON NUMPY LIBRARY

IMPORTING THE NUMPY LIBRARY

In [21]:
import numpy as np

CREATING VECTOR AND MATRIX USING Numpy array

In [ ]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]]) # matrix

In [ ]:
print(A)
print(type(A)) # type of object
print(A.size) # overal size (total number of elements)
print(A.shape) # number rows vs columns
print(A.ndim) # number of dimensions: 1 for vectors, 2 for matrices

In [ ]:
B = np.array([1,2,3,4]) #Vector

In [ ]:
print(A)
B

In [ ]:
B.size

In [ ]:
B.shape

In [ ]:
type(B)

CREATING MATRIX USING mat or matrix

In [ ]:
N = np.matrix([[1,2,3], [4,5,6], [7,8,9]])
print(N)
print(type(N))
print(N.size)
print(N.shape)

In [ ]:
M = np.mat([[1,2,3], [4,5,6], [7,8,9]])
print(M)
print(type(M))
print(M.size)
print(M.shape)

Advantage of using mat function over array for matrix

In [ ]:
# this is not the correct way to create a 3 by 2 matrix using np.array
M = np.array('1,2;3,4;5,6')
print(M)
print(type(M))
print(M.size)
print(M.shape)

In [ ]:
M = np.mat('1,2;3,4;5,6')
print(M)
print(type(M))
print(M.size)
print(M.shape)

CREATING VECTOR AND MATRIX USING random function

In [ ]:
V = np.random.randn(3)
print(V)
print(type(V))
print(V.size)
print(V.shape)

In [ ]:
M = np.random.randn(2,4)
print(M)
print(type(M))
print(M.size)
print(M.shape)

CREATING VECTOR AND MATRIX USING arange

In [ ]:
V = np.arange(8)
print(V)
print(type(V))
print(V.size)
print(V.shape)

In [ ]:
M = np.arange(8).reshape(2,4)
print(M)
print(type(M))
print(M.size)
print(M.shape)

ACCESS TO THE ELEMENTS OF THE ARRAY

In [ ]:
print('V = ', V)
print('M = ', M)

In [ ]:
print(V[1])

print(M[1,2])

In [ ]:
print(V[:1])

print(V[:2])

In [22]:
M = np.random.randn(4,3)

In [ ]:
print(np.round(M,2))

In [ ]:
print(np.round(M[:1,:],2))


In [ ]:
print(np.round(M[:1,:],2))


In [ ]:
print(np.round(M[:-2,:],2))

In [ ]:
M

In [ ]:
i = 0
for rows in M:
    i+=1
    print('row'+str(i), rows)

SPECIAL MATRICES

In [ ]:
np.eye(4)

In [ ]:
np.identity(3)

In [ ]:
np.ones(5)

In [ ]:
np.ones((3,2))

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((3,2))

RESHAPING MATRICES: reshape

In [23]:
print(M)
print(M.shape)

[[ 1.47528743 -0.21286259  2.14122439]
 [-0.86515305  0.83671015  1.46472716]
 [ 1.30235152  0.41122789  0.34416378]
 [ 0.83834238  1.18137106  0.4719949 ]]
(4, 3)


In [25]:
M2 = np.reshape(M, (3,4))
print(M2)
print(M2.shape)

[[ 1.47528743 -0.21286259  2.14122439 -0.86515305]
 [ 0.83671015  1.46472716  1.30235152  0.41122789]
 [ 0.34416378  0.83834238  1.18137106  0.4719949 ]]
(3, 4)


In [28]:
V = np.array([0,1,3,6])
print(V)
print(V.shape)
print(V.ndim)

[0 1 3 6]
(4,)
1


In [29]:
W = np.reshape(V,(4,1))
print(W)
print(W.shape)
print(W.ndim)

[[0]
 [1]
 [3]
 [6]]
(4, 1)
2


FLATTENING A MATRIX

In [30]:
A = np.random.randn(2,4)
B = A.flatten()

print('A = ', np.round(A,2))
print('Flatten of A = ', np.round(B,2))

A =  [[ 0.33 -0.1   1.93  1.6 ]
 [ 0.69  1.76  0.09  0.52]]
Flatten of A =  [ 0.33 -0.1   1.93  1.6   0.69  1.76  0.09  0.52]


ADDING/SUBTRACTING/MULTIPLYING SCALAR TO MATRIX

In [31]:
A = np.random.randn(4,4)
n = 10
B = A + n
print('A = ', np.round(A,2))
print('A + ',n,' = ', np.round(B,2))


A =  [[-0.14  1.53 -0.02 -0.91]
 [-0.55 -0.76 -0.03  0.3 ]
 [ 0.04  1.97  0.17 -0.37]
 [ 0.4  -0.16 -1.58  0.08]]
A +  10  =  [[ 9.86 11.53  9.98  9.09]
 [ 9.45  9.24  9.97 10.3 ]
 [10.04 11.97 10.17  9.63]
 [10.4   9.84  8.42 10.08]]


In [32]:
C = A - n
print('A = ', np.round(A,2))
print('A - ',n,' = ', np.round(C,2))

A =  [[-0.14  1.53 -0.02 -0.91]
 [-0.55 -0.76 -0.03  0.3 ]
 [ 0.04  1.97  0.17 -0.37]
 [ 0.4  -0.16 -1.58  0.08]]
A -  10  =  [[-10.14  -8.47 -10.02 -10.91]
 [-10.55 -10.76 -10.03  -9.7 ]
 [ -9.96  -8.03  -9.83 -10.37]
 [ -9.6  -10.16 -11.58  -9.92]]


In [33]:
D = A * n
print('A = ', np.round(A,2))
print('A * ',n,' = ', np.round(D,1))

A =  [[-0.14  1.53 -0.02 -0.91]
 [-0.55 -0.76 -0.03  0.3 ]
 [ 0.04  1.97  0.17 -0.37]
 [ 0.4  -0.16 -1.58  0.08]]
A *  10  =  [[ -1.4  15.3  -0.2  -9.1]
 [ -5.5  -7.6  -0.3   3. ]
 [  0.4  19.7   1.7  -3.7]
 [  4.   -1.6 -15.8   0.8]]


In [34]:
# ADDING A SCALAR TO SPECIFIC ROW/COLUMN

A[1,:] = A[1,:] + 3 # add to the second row only
print('A = ', np.round(A,2))

A[:,1] = A[:,1] + 3 # add to the second column only
print('A = ', np.round(A,2))

A =  [[-0.14  1.53 -0.02 -0.91]
 [ 2.45  2.24  2.97  3.3 ]
 [ 0.04  1.97  0.17 -0.37]
 [ 0.4  -0.16 -1.58  0.08]]
A =  [[-0.14  4.53 -0.02 -0.91]
 [ 2.45  5.24  2.97  3.3 ]
 [ 0.04  4.97  0.17 -0.37]
 [ 0.4   2.84 -1.58  0.08]]


ADD/SUBTRACT MATRICES

In [37]:
A = np.random.randn(3,4)
B = np.random.randn(3,4)
C = A + B
D = A - B
E = B - A

print('A = ', np.round(A,2))
print('B = ', np.round(B,2))
print('A + B = ', np.round(C,2))
print('A - B = ', np.round(D,2))
print('B - A = ', np.round(E,2))

A =  [[ 0.11  0.04 -0.76 -1.46]
 [-2.2  -1.32  1.48  0.71]
 [-0.5  -2.94 -1.66 -1.05]]
B =  [[ 2.02  1.02 -0.09 -0.7 ]
 [ 0.35  0.32 -0.19  0.36]
 [-0.78  0.57  1.11 -0.24]]
A + B =  [[ 2.13  1.06 -0.85 -2.16]
 [-1.85 -1.    1.29  1.07]
 [-1.27 -2.37 -0.55 -1.28]]
A - B =  [[-1.91 -0.98 -0.66 -0.76]
 [-2.55 -1.64  1.67  0.35]
 [ 0.28 -3.5  -2.77 -0.81]]
B - A =  [[ 1.91  0.98  0.66  0.76]
 [ 2.55  1.64 -1.67 -0.35]
 [-0.28  3.5   2.77  0.81]]


MULTIPLYING VECTORS

In [38]:
a = np.arange(4)
b = np.arange(4)+3
c = np.inner(a,b)
d = np.dot(a,b)
f = np.sum(a * b)

print('a = ', a)
print('b = ', b)
print('a.b = ', c)
print('a.b = ', d)
print('a.b = ', f)

a =  [0 1 2 3]
b =  [3 4 5 6]
a.b =  32
a.b =  32
a.b =  32


In [39]:
np.outer(a,b)

array([[ 0,  0,  0,  0],
       [ 3,  4,  5,  6],
       [ 6,  8, 10, 12],
       [ 9, 12, 15, 18]])

MULTIPLYING A MATRIX BY A SCALAR

In [40]:
A = np.random.randn(3,3)
n = 10
B = A*n
print('A = ', np.round(A,2))
print('B = ', np.round(B,1))

A =  [[ 0.7   0.44 -0.88]
 [ 1.55 -0.23 -1.08]
 [ 0.22 -1.7   0.25]]
B =  [[  7.    4.4  -8.8]
 [ 15.5  -2.3 -10.8]
 [  2.2 -17.    2.5]]


MULTIPLYING TWO MATRICES

In [41]:
A = np.random.randn(5,3)
B = np.random.randn(5,3)

C = A * B

print('A = ', np.round(A,2))
print('B = ', np.round(B,2))
print('A * B = ', np.round(C,2))

print('dimension A = ', A.shape)
print('dimension B = ', B.shape)
print('dimension A * B = ', C.shape)

A =  [[ 1.68 -0.06  0.22]
 [ 1.39  0.98 -0.79]
 [ 1.34 -1.39 -0.61]
 [-0.12 -0.92  0.17]
 [ 1.77  1.58 -1.36]]
B =  [[-0.19 -0.63 -1.09]
 [-0.45  1.36 -1.49]
 [-0.44 -0.29 -0.11]
 [-1.23  0.37 -0.3 ]
 [ 0.2  -0.81 -1.08]]
A * B =  [[-0.32  0.04 -0.24]
 [-0.63  1.33  1.18]
 [-0.59  0.4   0.07]
 [ 0.14 -0.34 -0.05]
 [ 0.36 -1.28  1.47]]
dimension A =  (5, 3)
dimension B =  (5, 3)
dimension A * B =  (5, 3)


In [42]:
A = np.random.randn(3,2)
B = np.random.randn(2,4)

# 3 METHODS:

# METHOD 1:
C = A.dot(B)

# METHOD 2:
D = np.dot(A,B)

# METHOD 3:
E = A @ B

print('A = ', np.round(A,2))
print('B = ', np.round(B,2))
print('Method 1: A . B = ', np.round(C,2))
print('Method 2: A . B = ', np.round(D,2))
print('Method 3: A . B = ', np.round(E,2))

print('dimension A = ', A.shape)
print('dimension B = ', B.shape)
print('dimension A . B = ', C.shape)

A =  [[-0.36 -1.5 ]
 [-0.2   0.98]
 [ 0.32  0.42]]
B =  [[-0.05 -0.33 -0.02  0.93]
 [-3.46 -0.4   0.74 -1.1 ]]
Method 1: A . B =  [[ 5.21  0.72 -1.11  1.31]
 [-3.37 -0.32  0.73 -1.26]
 [-1.45 -0.27  0.3  -0.15]]
Method 2: A . B =  [[ 5.21  0.72 -1.11  1.31]
 [-3.37 -0.32  0.73 -1.26]
 [-1.45 -0.27  0.3  -0.15]]
Method 3: A . B =  [[ 5.21  0.72 -1.11  1.31]
 [-3.37 -0.32  0.73 -1.26]
 [-1.45 -0.27  0.3  -0.15]]
dimension A =  (3, 2)
dimension B =  (2, 4)
dimension A . B =  (3, 4)


DIAGONAL OF A MATRIX: diagonal

In [43]:
A_diag = A.diagonal()

print('A = ', A)
print('diagonal  of A is:', A_diag)

A =  [[-0.36354062 -1.50328513]
 [-0.19844808  0.97882482]
 [ 0.32289293  0.41501611]]
diagonal  of A is: [-0.36354062  0.97882482]


TRACE OF A MATRIX: trace

In [44]:
A_trace = A.trace()

print('A = ', A)
print('Trace of A is:', A_trace)

A =  [[-0.36354062 -1.50328513]
 [-0.19844808  0.97882482]
 [ 0.32289293  0.41501611]]
Trace of A is: 0.6152842029721008


TRANSPOSING A MATRIX

In [45]:
A = np.random.randn(3,4)
A_tran = A.T

print('A = ', np.round(A,2))
print('Transpose of A = ', np.round(A_tran,2))

print('dimension A = ', A.shape)
print('dimension Transpose(A) = ', A_tran.shape)

A =  [[-2.08  0.01  0.38 -1.4 ]
 [-0.38 -0.87  0.42 -1.4 ]
 [ 0.6  -0.79 -0.29 -0.23]]
Transpose of A =  [[-2.08 -0.38  0.6 ]
 [ 0.01 -0.87 -0.79]
 [ 0.38  0.42 -0.29]
 [-1.4  -1.4  -0.23]]
dimension A =  (3, 4)
dimension Transpose(A) =  (4, 3)


# np.linalg 

In [52]:
import numpy as np
from numpy import linalg as LA

INVERTING A MATRIX

In [59]:
A = np.random.randn(4,4)
A = np.round(A,2)
print(A)

[[ 0.05  0.99 -0.95  0.92]
 [ 0.32 -1.08 -1.75 -1.2 ]
 [ 0.43  0.5   1.7   1.37]
 [-0.57  0.16 -0.2   1.23]]


In [53]:
# A_inv = np.linalg.inv(A)
A_inv = LA.inv(A)
A_inv = np.round(A_inv, 2)

print('A = ', A)
print('Inverse of A = ', A_inv)

print('dimension A = ', A.shape)
print('dimension Inverse(A) = ', A_inv.shape)

A =  [[-0.37  0.43 -0.13  1.81]
 [ 0.96 -0.88 -0.43  0.09]
 [ 0.34  0.02 -0.43  0.81]
 [-0.3  -0.28  0.06  0.  ]]
Inverse of A =  [[ 0.69  1.11 -1.67 -2.54]
 [-0.26 -0.79  0.66 -1.45]
 [ 2.26  1.87 -5.27 -2.78]
 [ 0.92  0.55 -0.88 -0.37]]
dimension A =  (4, 4)
dimension Inverse(A) =  (4, 4)


DETERMINANT OF MATRIX: det

In [55]:
print('A = ', A)
print('Shape of Matrix A is:', A.shape)
print('Determinant of Matrix A is:', LA.det(A))

A =  [[-0.37  0.43 -0.13  1.81]
 [ 0.96 -0.88 -0.43  0.09]
 [ 0.34  0.02 -0.43  0.81]
 [-0.3  -0.28  0.06  0.  ]]
Shape of Matrix A is: (4, 4)
Determinant of Matrix A is: 0.18701096


RANK OF A MATRIX: matrix_rank

In [57]:
print('A = ', A)
print('Shape of Matrix A is:', A.shape)
print('Rank of Matrix A is:', LA.matrix_rank(A))

A =  [[-0.37  0.43 -0.13  1.81]
 [ 0.96 -0.88 -0.43  0.09]
 [ 0.34  0.02 -0.43  0.81]
 [-0.3  -0.28  0.06  0.  ]]
Shape of Matrix A is: (4, 4)
Rank of Matrix A is: 4


EIGEN VALUES AND EIGEN VECTORS OF A MATRIX: eig

In [62]:
eigenvalues, eigenvectors = LA.eig(A)

print('A = ', A)
print('Eigen values of A:', eigenvalues)
print('Number of the Eigenvalues',eigenvalues.size)
print('Eigen vctors of A:', eigenvectors)
print('Shape of the Eigenvectors',eigenvectors.shape)

A =  [[ 0.05  0.99 -0.95  0.92]
 [ 0.32 -1.08 -1.75 -1.2 ]
 [ 0.43  0.5   1.7   1.37]
 [-0.57  0.16 -0.2   1.23]]
Eigen values of A: [-1.07809548+0.j          0.71367129+1.20999542j  0.71367129-1.20999542j
  1.55075289+0.j        ]
Number of the Eigenvalues 4
Eigen vctors of A: [[-0.54117602+0.j          0.73918467+0.j          0.73918467-0.j
  -0.52824228+0.j        ]
 [ 0.81913026+0.j          0.22062842+0.2080331j   0.22062842-0.2080331j
  -0.57019415+0.j        ]
 [ 0.02900779+0.j         -0.08780464-0.51456107j -0.08780464+0.51456107j
   0.54488905+0.j        ]
 [-0.18791667+0.j          0.2051512 +0.21698292j  0.2051512 -0.21698292j
   0.31453879+0.j        ]]
Shape of the Eigenvectors (4, 4)


NORM OF A VECTOR/MATRIX: norm

In [63]:
# Vector
a = np.arange(6)
n = LA.norm(a)

print('a = ', a)
print('norm(a) = ', n)


a =  [0 1 2 3 4 5]
norm(a) =  7.416198487095663


In [65]:
a = np.array([0,0])
b = np.array([2,1])
d = LA.norm(a-b)
print('Euclidian Distance between a and b =', d)

Euclidian Distance between a and b = 2.23606797749979


In [68]:
# Matrix
A = np.arange(4).reshape(2,2)
N = LA.norm(A)

print('A = ', A)
print('norm(A) = ', N)


A =  [[0 1]
 [2 3]]
norm(A) =  3.7416573867739413


SOLVING LINEAR MATRIX EQUATION OR SYSTEM OF SCALAR EQUATIONS

Exact solution: solve

In [70]:
A = np.array([[4,-3],[2,5]])
b = np.array([8,11])
x = LA.solve(A, b)

for i in range(len(x)):
    print('x'+str(i+1)+' = ',x[i])

x1 =  2.8076923076923075
x2 =  1.0769230769230769


In [72]:
if np.allclose(np.dot(A,x),b):
    print('The solution is correct!')
else:
    print('The solution is NOT correct!')
    
print(np.allclose(np.dot(A,x),b))

The solution is correct!
True


The Least Square solution: lstsq

In [74]:
A = np.array([[4,-3],[2,5]])
b = np.array([8,11])
x, res, rnk, s = LA.lstsq(A, b)

print(x)

[2.80769231 1.07692308]


C:\Users\ali\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


In [75]:
if np.allclose(np.dot(A,x),b):
    print('The solution is correct!')
else:
    print('The solution is NOT correct!')

The solution is correct!


SINGULAR VALUE DECOMPOSITION: svd

In [76]:
A = np.array([[1,2,3],[4,5,6]])
u,s,Vh = LA.svd(A)


In [80]:
print(u)

[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]


In [81]:
print(s)

[9.508032   0.77286964]
